services:
  app:
    build: .
    container_name: timelycapsule-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - timelycapsule-net

  db:
    image: mongo:6.0
    container_name: timelycapsule-db
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - timelycapsule-net

volumes:
  db_data:

networks:
  timelycapsule-net:
    driver: bridge
